# Generated by Django 4.2 on 2023-06-26 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-publish'], 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-first_name', '-last_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=10),
        ),
        migrations.AlterField(
            model_name='productcombinamtions',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='users',
            name='forgotCodeSentTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('RG', 'Registered'), ('SN', 'Sent')], default='DF', max_length=10),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['-publish'], name='shop_produc_publish_794e86_idx'),
        ),
    ]
