# Generated by Django 4.2 on 2023-07-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productcombinamtions',
            options={'verbose_name': 'Комбинация продуктов', 'verbose_name_plural': 'Комбинации продуктов'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['subcategory_name'], 'verbose_name': 'Субкатегория', 'verbose_name_plural': 'Субкатегории'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcombinamtions',
            name='status',
            field=models.CharField(choices=[('AVBL', 'Available'), ('NAVBL', 'Not_Available')], default='NAVBL', max_length=10),
        ),
        migrations.AlterField(
            model_name='productcombinamtions',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='shop_catego_categor_cb48d9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['subcategory_name'], name='shop_subcat_subcate_39593e_idx'),
        ),
    ]
